.TH "17114008_Aman_Jaiswal/Q2 Directory Reference" 3 "Thu Aug 1 2019" "Version version 1" "Assignment-2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
17114008_Aman_Jaiswal/Q2 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBboth\&.c\fP"
.br
.RI "A C program to demonstrate Orphan and zombie Process\&. "
.ti -1c
.RI "file \fBorphan\&.c\fP"
.br
.RI "A C program to demonstrate Orphan Process\&.Parent process finishes execution while the child process is running\&. The child process becomes orphan\&. "
.ti -1c
.RI "file \fBzombie\&.c\fP"
.br
.RI "A C program to demonstrate Zombie Process\&.Child becomes Zombie as parent is sleeping when child process exits\&. "
.in -1c
