.TH "17114008_Aman_Jaiswal/Q1 Directory Reference" 3 "Thu Aug 1 2019" "Version version 1" "Assignment-2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
17114008_Aman_Jaiswal/Q1 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTCP_CLIENT\&.c\fP"
.br
.RI "Create TCP socket\&.connect newly created client socket to server\&. "
.ti -1c
.RI "file \fBTCP_SERVER\&.c\fP"
.br
.RI "Create TCP socket\&.connect newly created client socket to server\&. "
.in -1c
