.TH "17114008_Aman_Jaiswal/Q1/TCP_SERVER.c" 3 "Thu Aug 1 2019" "Version version 1" "Assignment-2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
17114008_Aman_Jaiswal/Q1/TCP_SERVER.c \- Create TCP socket\&.connect newly created client socket to server\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <netdb\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX\fP   80"
.br
.ti -1c
.RI "#define \fBPORT\fP   8080"
.br
.ti -1c
.RI "#define \fBSA\fP   struct sockaddr"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfunc\fP (int sockfd)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Create TCP socket\&.connect newly created client socket to server\&. 


.PP
\fBAuthor:\fP
.RS 4
Aman Jaiswal 
.RE
.PP
\fBDate:\fP
.RS 4
01/08/2019 
.RE
.PP

.PP
Definition in file \fBTCP_SERVER\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX   80"

.PP
Definition at line 14 of file TCP_SERVER\&.c\&.
.SS "#define PORT   8080"

.PP
Definition at line 15 of file TCP_SERVER\&.c\&.
.SS "#define SA   struct sockaddr"

.PP
Definition at line 16 of file TCP_SERVER\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void func (int sockfd)"
Function designed for chat between client and server\&. 
.PP
\fBAuthor:\fP
.RS 4
Aman Jaiswal 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIsockfd-\fP socket file descriptor 
.RE
.PP
\fBDate:\fP
.RS 4
2/28/2009 
.RE
.PP

.PP
Definition at line 24 of file TCP_SERVER\&.c\&.
.SS "int main ()"
Driver function 
.PP
\fBAuthor:\fP
.RS 4
Aman Jaiswal 
.RE
.PP
\fBDate:\fP
.RS 4
2/28/2009 
.RE
.PP

.PP
Definition at line 57 of file TCP_SERVER\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Assignment-2 from the source code\&.
